stages:
  - lint

lint:
  image: registry.gitlab.com/jameshiew/toolbox/luaci:20210916-115155-f4045b 
  stage: lint
  script:
    - luacheck --version
    - luacheck .
    - stylua --version
    - stylua --verbose --check .

